export const mock_description =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus a sem ut sagittis. Ut imperdiet mi ut turpis vehicula, vitae viverra eros laoreet. Nunc hendrerit at nulla ac commodo. Pellentesque iaculis velit ac accumsan ullamcorper. Aliquam tempus turpis sed purus porttitor viverra. Aliquam erat volutpat. Mauris pretium cursus dignissim. Quisque et porta nisi, eget vulputate purus. Suspendisse non pellentesque tortor. Nam viverra nunc at augue molestie pulvinar. Etiam sit amet ullamcorper tortor. Morbi dapibus erat id magna tincidunt, consequat pulvinar nunc maximus. Cras porta, est a eleifend iaculis, urna diam consectetur nisi, vitae vehicula sem tellus dignissim risus. Aenean in mi dui. Donec viverra quis nisi eu vestibulum. Nullam vulputate lectus arcu, eu egestas risus vehicula nec. Sed gravida risus a ex lacinia, vitae vulputate metus rhoncus. Proin scelerisque augue dapibus, euismod lorem quis, aliquet dolor. Mauris fermentum sapien nisl, nec condimentum dui placerat at. Curabitur accumsan ipsum et sem vehicula, et suscipit ligula auctor. Donec id dapibus tellus. Quisque id elit faucibus, egestas nisi sed, porta nulla. Duis in nulla sed sem pharetra sodales quis ac lorem. Duis commodo vel leo ut eleifend. Vivamus rhoncus, ligula sit amet sagittis maximus, nulla lacus pellentesque lectus, et sollicitudin nisi magna non erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In auctor est in vestibulum maximus. Etiam venenatis risus eget luctus tincidunt. Mauris consectetur venenatis efficitur. In pharetra elementum lacinia. Suspendisse nibh massa, vehicula ac est at, pretium congue risus. Suspendisse iaculis dui ac erat ornare, nec ultrices augue semper. Vivamus posuere vulputate bibendum. Praesent pulvinar magna nibh, ac dictum velit imperdiet ac. Sed luctus ex urna, sed pharetra libero ullamcorper vitae. Donec eu vulputate turpis, sit amet mollis nulla.";

export const mock_genres = [
  "Action/Adventure",
  "Children",
  "Classic",
  "Contemporary",
  "Fantasy",
  "Graphic novel",
  "Historical",
  "Horror",
  "LGBTQ+",
  "Literary",
  "Mystery",
  "New adult",
  "Romance",
  "Satire",
  "Science",
  "Short story",
  "Thriller",
  "Western",
  "Women",
  "Young adult",
  "Art & photography",
  "Autobiography/Memoir",
  "Biography",
  "Essays",
  "Food & drink",
  "History",
  "How-To/Guides",
  "Humanities & social sciences",
  "Humor",
  "Parenting",
  "Philosophy",
  "Religion & spirituality",
  "Science & technology",
  "Self-help",
  "Travel",
  "True crime",
];
